compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      typescript: '*'
  '@lerna/github-client@*':
    peerDependencies:
      '@octokit/core': '*'
  '@lerna/publish@*':
    peerDependencies:
      '@octokit/core': '*'
  '@lerna/version@*':
    peerDependencies:
      '@octokit/core': '*'
  '@octokit/rest@*':
    peerDependencies:
      '@octokit/core': '*'
  graphql-config@*:
    peerDependencies:
      typescript: '*'
  lerna@*:
    peerDependencies:
      '@octokit/core': '*'
  polyfill-library@*:
    peerDependencies:
      '@types/node': '*'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
