nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@lerna/github-client@*":
    peerDependencies:
      "@octokit/core": "*"
  "@lerna/publish@*":
    peerDependencies:
      "@octokit/core": "*"
  "@lerna/version@*":
    peerDependencies:
      "@octokit/core": "*"
  "@octokit/rest@*":
    peerDependencies:
      "@octokit/core": "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
  lerna@*:
    peerDependencies:
      "@octokit/core": "*"
  polyfill-library@*:
    peerDependencies:
      "@types/node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
